# Generated by Django 5.2.13 on 2026-07-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='secret_note',
            field=models.TextField(default='Secret note.'),
        ),
    ]
